### PR TITLE
Commit CMCP Python Modules from sr52 Project

### PR DESCRIPTION
**Pull request by mwe-sandag**
Most up-to-date scripts for CMCP Reporting. This script should form the base of future CMCP script modifications.
Scripts will require updating when stored procedures are moved to long-term database.
Database specifications screened.

### CODE REVIEW

**Review by anneku — CHANGES_REQUESTED** [review]
Is an excel template needed for this code to run?  Maybe that should be included in the resources folder?

**Review by anneku — APPROVED** [review]
Looks good.  There was a reference to an image in the README but no image.  I like the error catching with the database config yml, since easy to forget to add the file.  I wonder if we should have a blank template for the yml.

**Comment by mwe-sandag** [comment]
> Looks good. There was a reference to an image in the README but no image. I like the error catching with the database config yml, since easy to forget to add the file. I wonder if we should have a blank template for the yml.

**Comment by mwe-sandag** [comment]
> Looks good. There was a reference to an image in the README but no image. I like the error catching with the database config yml, since easy to forget to add the file. I wonder if we should have a blank template for the yml.

I believe I have addressed your comments here and in person. Missing examples from the README.md and a dummy database-specs.yaml file were added. Missing Excel templates were pushed to the resources file.
 
Additionally, absolute paths were also changed to relative paths in settings.py.

**Pull request merged**
