### PR TITLE
Commit CMCP Python Modules from sr52 Project

### PR DESCRIPTION
**Pull request by mwe-sandag**
Pushing existing code to ABM-Reporting GitHub for version control + transparency.
Alterations should be made when [WS] stored procedures + functions are moved to appropriate long-term databases.
Alterations to make these scripts project ambiguous should be considered.

### CODE REVIEW

**Review by anneku — COMMENTED** [review]
please remove the .idea folder and add to git ignore.

**Comment by mwe-sandag** [comment]
@anneku .bak and .idea files removed

**Review by anneku — COMMENTED** [review]
why is there an empty text file?

**Review by anneku — COMMENTED** [review]
Why is the README being updated?

**Comment by mwe-sandag** [comment]
> Why is the README being updated?

Unintentional reversion of this commit bc of out-of-date main branch: 
https://github.com/SANDAG/ABM-Reporting/commit/d43811c249940020138f3a3ba7e98b27afcefff7
Fixed. Apologies, shaking off the rust

**Review by anneku — COMMENTED** [review]
Please remove references from settings.py

**Pull request closed without merging**
